#title: Md. Ahnaf Nafi
logo: /assets/img/Crop.jpeg
#description: >- 
  #I'm an Urban Planner, working on Data Science to do a batter planned city    
 # [Email](mailto:ahnafnafi98@gmail.com)
  
#show_downloads: true
#theme: jekyll-theme-minimal

title: Ahnaf Nafi's Academic Website
email: ahnafnafi98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an Urban Planner, working on Data Science to do a batter planned city 
baseurl: "/ahnafnafi" # the subpath of your site, e.g. /blog
url: "https://nafixdata.github.io" # the base hostname & protocol for your site

theme: jekyll-theme-minimal

# Author Information
author:
  name: Ahnaf Nafi
  email: ahnafnafi98@gmail.com
  bio: "Researcher in [your field]. Focused on [specific topics]."

# Navigation Links 
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "_pages/about.md"
  - title: "Projects"
    url: "_pages/projects/"
  - title: "Portfolio"
    url: "_pages/portfolio/"

# Social Links
social_links:
  github: https://github.com/nafixdata
  linkedin: https://linkedin.com/in/ahnafnafi
  twitter: https://twitter.com/ahnafnafi

# Enable plugins
plugins:
  - jekyll-feed
