title: Md. Ahnaf Nafi
logo: /assets/img/Crop.jpeg
description: >- 
  I'm an Urban Planner, working on Data Science to do a batter planned city    
show_downloads: true
theme: jekyll-theme-minimal

# Reading Files
include:
  - _pages

