title: Md. Ahnaf Nafi
logo: /assets/img/Crop.jpeg
description: >- 
  I'm an Urban Planner, working on Data Science to do a batter planned city  
  email: ahnafnafi98@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
