title: Md. Ahnaf Nafi
logo: /assets/img/Crop.jpeg
description: >- 
  I'm an Urban Planner, working on Data Science to do a batter planned city    
show_downloads: true
theme: jekyll-theme-minimal

header_pages:
  - index.md
  - about.md
  - portfolio.md
  - projects.md
  
# Reading Files
include:
  - _pages

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Portfolio"
    url: "/portfolio/"
